Feature/flow 2360 - Fixing ui-core npm vulnerabilities
manywho/ui-runtime pull request #86
Opened 2020-12-03 16:27 UTC by TomFullalove

I had to npm audit fix --force to fix these 5 security issues

+ chokidar-cli@2.1.0 + ava@3.13.0 + react@17.0.1 + webpack@5.4.0 + react-dom@17.0.1

I fixed the webpack.development.config.js to use new standards and build are now successful but have errors.

I fixed all linting errors in code and tests and upgraded packages that used webpack so they worked with the latest webpack.

Then there were some manual peer dependencies to install, one of which required a major typescript update.

uglifyjs-webpack-plugin is deprecated and not needed with the newer version of webpack so was removed.

After this the ui-core build succeeds with no errors.

Then I went onto the ava tests, ava was updated automatically from 0.22.0 to 3.13.0

All of the tests that use callbacks and serial needed to use serial first, then cb.

Some tests now running serially expect different numbers of calls because they are not being interfered with by other parallel running tests, the code makes sense that they should expect this lesser amount of calls.

Some t.throws tests in engine.ts have been changed so we wait for the catch and then check the error message, this still checks for the same results as before.

In component.ts, some duplicated tests fixed, and ReactDOM stub added to fix mocking issues.

npm start and npm test complete with no errors.

2020-12-07 11:26 UTC, TomFullalove commented
Summary after FLOW-870 merge:

### ui-core subrepo

`npm test` all tests pass no errors

`npm start` does run and build successfully, but now shows linting errors for all repos. This is because the tsconfig.json was removed from ui-core in FLOW-870 and the only one that exists is in the ui-runtime parent folder. As I understand it, npm starts for subrepos are not planned to be used in the future as the parent repo should be used to start the project.



### ui-runtime parent repo

`npm run build` runs without errors

`npm start` runs without errors

`npm run lint:core` DOES have linting errors. This is expected after FLOW-870 and there will be another ui-runtime ticket made to fix these

2020-12-09 14:26 UTC, jamesbrattBoomi requested changes
Nice work. Just something to check in the prod webpack config.
Also, I think an update to React/React DOM in the Tooling will need to happen.

2020-12-16 10:42 UTC, dshoulders commented
I've removed the webpack config files as they are no longer used. The project is built using the webpack config files in the root ui-runtime directory.
I've run npx depcheck to find dependencies listed in package.json that are not used. I've removed the dependencies that were found, run the tests and run the project in the browser with no errors.
I haven't downgraded react back to v16 because it made some tests fail. The version loaded in the browser is not controlled by npm dependencies and is loaded externally, so that version will not change.

2020-12-16 11:32 UTC, jamesbrattBoomi approved these changes

2020-12-16 12:56 UTC, merged